apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "k8s-authentication-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-authentication-proxy.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "k8s-authentication-proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.proxy.image.registry }}/{{ .Values.proxy.image.repository }}/{{ .Values.proxy.image.name }}:{{ .Chart.AppVersion }}
          ports:
            - containerPort: {{ .Values.proxy.service.port }}
              name: nginx
          volumeMounts:
            - mountPath: {{ .Values.proxy.configuration.path }}/{{ .Values.proxy.configuration.file }}
              name: {{ template "k8s-authentication-proxy.configuration.name" . }}
              subPath: {{ .Values.proxy.configuration.file }}
            - mountPath: {{ .Values.proxy.configuration.path }}/{{ template "k8s-authentication-proxy.credentials.name" . }}
              name: {{ template "k8s-authentication-proxy.credentials.name" . }}
              subPath: {{ template "k8s-authentication-proxy.credentials.name" . }}
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
      volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: {{ .Values.proxy.configuration.file }}
              path: {{ .Values.proxy.configuration.file }}
            name: {{ template "k8s-authentication-proxy.configuration.name" . }}
          name: {{ template "k8s-authentication-proxy.configuration.name" . }}
        - secret:
            secretName: {{ template "k8s-authentication-proxy.credentials.name" . }}
          name: {{ template "k8s-authentication-proxy.credentials.name" . }}