apiVersion: kubernetes-client.io/v1
king: ExternalSecret
metadata:
  name: {{ template "k8s-authentication-proxy.credentials.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  backendType: vault
  kvVersion: 1
  data:
    - name: {{ template "k8s-authentication-proxy.credentials.name" . }}
      key: external-secret/k8s-authentication-proxy
      property: user-and-password
