apiVersion: v1
data: 
  {{ template "k8s-authentication-proxy.credentials.name" . }}: {{ .Values.proxy.credentials.base64 }}
kind: Secret
metadata:
  name: {{ template "k8s-authentication-proxy.credentials.name" . }}
type: Opaque