apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "k8s-authentication-proxy.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: {{ .Values.proxy.service.port }}-tcp
    port: {{ .Values.proxy.service.port }}
    protocol: TCP
    targetPort: {{ .Values.proxy.service.port }}
  selector:
    {{- include "k8s-authentication-proxy.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP